 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/club_infos", type: :request do
  # ClubInfo. As you add validations to ClubInfo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ClubInfo.create! valid_attributes
      get club_infos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      club_info = ClubInfo.create! valid_attributes
      get club_info_url(club_info)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_club_info_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      club_info = ClubInfo.create! valid_attributes
      get edit_club_info_url(club_info)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ClubInfo" do
        expect {
          post club_infos_url, params: { club_info: valid_attributes }
        }.to change(ClubInfo, :count).by(1)
      end

      it "redirects to the created club_info" do
        post club_infos_url, params: { club_info: valid_attributes }
        expect(response).to redirect_to(club_info_url(ClubInfo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ClubInfo" do
        expect {
          post club_infos_url, params: { club_info: invalid_attributes }
        }.to change(ClubInfo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post club_infos_url, params: { club_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested club_info" do
        club_info = ClubInfo.create! valid_attributes
        patch club_info_url(club_info), params: { club_info: new_attributes }
        club_info.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the club_info" do
        club_info = ClubInfo.create! valid_attributes
        patch club_info_url(club_info), params: { club_info: new_attributes }
        club_info.reload
        expect(response).to redirect_to(club_info_url(club_info))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        club_info = ClubInfo.create! valid_attributes
        patch club_info_url(club_info), params: { club_info: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested club_info" do
      club_info = ClubInfo.create! valid_attributes
      expect {
        delete club_info_url(club_info)
      }.to change(ClubInfo, :count).by(-1)
    end

    it "redirects to the club_infos list" do
      club_info = ClubInfo.create! valid_attributes
      delete club_info_url(club_info)
      expect(response).to redirect_to(club_infos_url)
    end
  end
end
