 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/consent_forms", type: :request do
  # ConsentForm. As you add validations to ConsentForm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ConsentForm.create! valid_attributes
      get consent_forms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      consent_form = ConsentForm.create! valid_attributes
      get consent_form_url(consent_form)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_consent_form_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      consent_form = ConsentForm.create! valid_attributes
      get edit_consent_form_url(consent_form)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ConsentForm" do
        expect {
          post consent_forms_url, params: { consent_form: valid_attributes }
        }.to change(ConsentForm, :count).by(1)
      end

      it "redirects to the created consent_form" do
        post consent_forms_url, params: { consent_form: valid_attributes }
        expect(response).to redirect_to(consent_form_url(ConsentForm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ConsentForm" do
        expect {
          post consent_forms_url, params: { consent_form: invalid_attributes }
        }.to change(ConsentForm, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post consent_forms_url, params: { consent_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested consent_form" do
        consent_form = ConsentForm.create! valid_attributes
        patch consent_form_url(consent_form), params: { consent_form: new_attributes }
        consent_form.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the consent_form" do
        consent_form = ConsentForm.create! valid_attributes
        patch consent_form_url(consent_form), params: { consent_form: new_attributes }
        consent_form.reload
        expect(response).to redirect_to(consent_form_url(consent_form))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        consent_form = ConsentForm.create! valid_attributes
        patch consent_form_url(consent_form), params: { consent_form: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested consent_form" do
      consent_form = ConsentForm.create! valid_attributes
      expect {
        delete consent_form_url(consent_form)
      }.to change(ConsentForm, :count).by(-1)
    end

    it "redirects to the consent_forms list" do
      consent_form = ConsentForm.create! valid_attributes
      delete consent_form_url(consent_form)
      expect(response).to redirect_to(consent_forms_url)
    end
  end
end
