 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/donors", type: :request do
  # Donor. As you add validations to Donor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Donor.create! valid_attributes
      get donors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      donor = Donor.create! valid_attributes
      get donor_url(donor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_donor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      donor = Donor.create! valid_attributes
      get edit_donor_url(donor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Donor" do
        expect {
          post donors_url, params: { donor: valid_attributes }
        }.to change(Donor, :count).by(1)
      end

      it "redirects to the created donor" do
        post donors_url, params: { donor: valid_attributes }
        expect(response).to redirect_to(donor_url(Donor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Donor" do
        expect {
          post donors_url, params: { donor: invalid_attributes }
        }.to change(Donor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post donors_url, params: { donor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested donor" do
        donor = Donor.create! valid_attributes
        patch donor_url(donor), params: { donor: new_attributes }
        donor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the donor" do
        donor = Donor.create! valid_attributes
        patch donor_url(donor), params: { donor: new_attributes }
        donor.reload
        expect(response).to redirect_to(donor_url(donor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        donor = Donor.create! valid_attributes
        patch donor_url(donor), params: { donor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested donor" do
      donor = Donor.create! valid_attributes
      expect {
        delete donor_url(donor)
      }.to change(Donor, :count).by(-1)
    end

    it "redirects to the donors list" do
      donor = Donor.create! valid_attributes
      delete donor_url(donor)
      expect(response).to redirect_to(donors_url)
    end
  end
end
