 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/event_calendars", type: :request do
  # EventCalendar. As you add validations to EventCalendar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EventCalendar.create! valid_attributes
      get event_calendars_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      event_calendar = EventCalendar.create! valid_attributes
      get event_calendar_url(event_calendar)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_event_calendar_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      event_calendar = EventCalendar.create! valid_attributes
      get edit_event_calendar_url(event_calendar)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EventCalendar" do
        expect {
          post event_calendars_url, params: { event_calendar: valid_attributes }
        }.to change(EventCalendar, :count).by(1)
      end

      it "redirects to the created event_calendar" do
        post event_calendars_url, params: { event_calendar: valid_attributes }
        expect(response).to redirect_to(event_calendar_url(EventCalendar.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EventCalendar" do
        expect {
          post event_calendars_url, params: { event_calendar: invalid_attributes }
        }.to change(EventCalendar, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post event_calendars_url, params: { event_calendar: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested event_calendar" do
        event_calendar = EventCalendar.create! valid_attributes
        patch event_calendar_url(event_calendar), params: { event_calendar: new_attributes }
        event_calendar.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the event_calendar" do
        event_calendar = EventCalendar.create! valid_attributes
        patch event_calendar_url(event_calendar), params: { event_calendar: new_attributes }
        event_calendar.reload
        expect(response).to redirect_to(event_calendar_url(event_calendar))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        event_calendar = EventCalendar.create! valid_attributes
        patch event_calendar_url(event_calendar), params: { event_calendar: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested event_calendar" do
      event_calendar = EventCalendar.create! valid_attributes
      expect {
        delete event_calendar_url(event_calendar)
      }.to change(EventCalendar, :count).by(-1)
    end

    it "redirects to the event_calendars list" do
      event_calendar = EventCalendar.create! valid_attributes
      delete event_calendar_url(event_calendar)
      expect(response).to redirect_to(event_calendars_url)
    end
  end
end
